

# School Data

We were able to find a variety of useful, longitudinal data provided by the Wake County Public School System.
While our analysis mainly focuses on using Free and Reduced-Price Lunch Program (FR Lunch Program) information, we wanted to provide these additional resources in case they are useful to you now or in the future.

Here we plot the number of times a school shows up in the TGCP data (this includes a client attending a school or any of their family members) with the number of students on the FR Lunch Program at that school. We also provide the percentage of the student body at a given school on the FR Lunch Program on the vertical axis. One use case for this information is to recognize unmet need. There may be certain schools that have many students (and/or a high percentage of the student body) participating in a lunch program that do not yet know about The Green Chair Project. Reaching out to the families, faculty, and guidance counselors at these schools may identify communities that would benefit from The Green Chair Project's services.

Additionally, it shows where the current Green Chair Project resources are being allocated. For example, some schools with a very high percentage of students on a lunch program are most prevalent in The Green Chair Project clients. These schools include Baileywick Road Elementary, Barwell Road Elementary, Conn Elementary, Powell Elementary, Oberlin Middle, and Zebulon Middle.

```{r  echo = FALSE, message = FALSE, warning = FALSE}
library(readxl)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(here)
i_am("school_data/school_data.Rmd")

#read excel document 
statcom_data <- read_csv(here("cleaned_STATCOM_data.csv"))

source(here("school_data/clean_school_names.R"))

school_col_names <- tidyselect::vars_select(colnames(statcom_data), contains('School', ignore.case = TRUE)) 

for(col_name in school_col_names){
  statcom_data[[col_name]] = clean_school_names(statcom_data %>% dplyr::select(col_name, ClientZipCode))$school_names
}

school_cols = unlist(statcom_data %>% dplyr::select(school_col_names))

count = table(school_cols, useNA="no")

school_count_df <- data.frame(school_name = names(count),
                     tgcp_count = as.integer(count))

lunch_data = read.csv(here("school_data/data/lunches_2020_2021.csv"))

lunch_data = lunch_data %>% dplyr::select(SCHOOL.NAME, FREE.and.REDUCED, FR.PERCENTAGE)

school_lunch = merge(school_count_df, lunch_data, by.x = "school_name", by.y = "SCHOOL.NAME")
school_lunch$FREE.and.REDUCED = as.numeric(school_lunch$FREE.and.REDUCED)
school_lunch$FR.PERCENTAGE = as.numeric(sub("%", "", school_lunch$FR.PERCENTAGE))


ggplot(school_lunch, aes(x=tgcp_count, y=FREE.and.REDUCED)) + 
  geom_point() + 
  geom_text(
    label=school_lunch$school_name,
    size = 3,
    nudge_x = 0.25, nudge_y = 0.25, 
    check_overlap = TRUE
  )  + 
  ylab("# of students on FR Lunch Program") +
  xlab("# of times school present in TGCP data")


ggplot(school_lunch, aes(x=tgcp_count, y=FR.PERCENTAGE)) + 
  geom_point() + 
  geom_text(
    label=school_lunch$school_name,
    size = 3,
    nudge_x = 0.25, nudge_y = 0.25, 
    check_overlap = TRUE
  ) + 
  ylab("% of students on FR Lunch Program") +
  xlab("# of times school present in TGCP data")

```


To start, [**here you can find**](https://www.wcpss.net/domain/100) a summary of the current status of the WCPSS.
This includes number of schools, employees, number of students on the Free and Reduced-Price Lunch Program, and more.
Additionally, they provide a _Reports by year_ section.
This breaks the information out at the school level.
This is where we obtained the Free and Reduced-Price Lunch Program data for each school.
They also offer ethnicity breakdowns, limited English proficiency rates, and special education services.
[**You can view the spreadsheet for the 2020-2021 school year here**](https://docs.google.com/spreadsheets/d/1Q7_HttWQBxRJfEGsvVl6Xf8slbLqxvuQvJ9Fz3hcL4k/edit#gid=1941273913), with previous years available on their website.


We also found a variety of information from [**the North Carolina Department of Public Instruction (NC DPI)**](https://www.dpi.nc.gov/districts-schools).
Some variables include [**cohort graduation rate, ACT results, and SAT and AP results**](https://www.dpi.nc.gov/districts-schools/testing-and-school-accountability/school-accountability-and-reporting).
These data are again broken up by school and include other school districts along with Wake County.
These were not the focus of our analysis, as there are often biases in these scores; however we wanted to provide the resource in you find other uses for it.
NC DPI also provides [**discipline and dropout data**](https://www.dpi.nc.gov/data-reports/dropout-and-discipline-data/discipline-alp-and-dropout-annual-reports#2018-19).
This includes tables about crime, dropout rates and counts, and suspensions.
We found this data to be mostly prevalent to high schools and less so in elementary and middle schools.

[**Finally, here is a nice visualization about postsecondary enrollment in North Carolina high schools.**](https://www.nccommunitycolleges.edu/analytics/dashboards/postsecondary-enrollment-high-school)
It allows options to change charts to look at breakdowns for particular schools.
Since this data was also focused exclusively on high schools, we did not make use of it ourselves.