```{r echo = FALSE}
library(readxl)
library(tidyverse)
library(here)
i_am("Long Format Data set/beds_by_people.Rmd")
#read excel document 
tgcp_demog <- read_excel(here("STATCOM_data.xlsx"), col_types = "text")
#rename tghe columns 
tgcp_demog <- rename(tgcp_demog, Id = `...1`)


#table(tgcp_demog$TotalHHNumber,

#convert the data set from wide format to longer format (by roll up the household Member Information and drop the missing values as necessary)
Longer_Format <- pivot_longer(tgcp_demog,col = 15:118,names_to = "HHMemberInfo",values_to = "HHMemberInfoAnswer",values_drop_na = TRUE) 


```


```{r }
#unite the client last name and client first name 
C <- unite(Longer_Format,ClientName, ends_with("Name"), sep = " ", na.rm = FALSE)

#unite the HHMemberInfo and InfoAnswer into one col with ":" separate. 
D <- unite(C,HHMemberInfo, starts_with("HHMemberInfo"), sep = ": ", na.rm = FALSE)


# convert the necessary variables from char to numeric values 
E <- D[, c(1,2,5,13,14,20,21)] <- sapply(D[,c(1,2,5,13,14,20,21)], as.numeric)
#str(D)

#create a new column  containing number of beds total in the household (adding QueensBed and TwinBeds)
F <- mutate(D,Beds = QueenBeds+TwinBeds)


#delete cols: QueensBeds and TwinsBeds
G <- subset(F, select = -c(TwinBeds,QueenBeds) )


#trying to deal with the ClientGender and Client Age issues since ClientAge contains some gender info that are not stated in the ClientGender col 

H <- G %>%
  mutate(ClientGenderFill = case_when(
    endsWith(ClientAge, "Male") ~ "Male",
    endsWith(ClientAge, "Female") ~ "Female"
    
  ))
```


```{r pressure, echo=FALSE}
# View(H)

#table(H$Race,H$ClientAge)
P <-H %>% group_by(ClientName) %>% filter(HHMemberInfo == c('TotalHHNumber: '))

P <- H %>% group_by(ClientName) %>% filter(HHMemberInfo == c('TotalHHNumber: 2.0'))
Y <- H %>% group_by(ClientName) %>% filter(HHMemberInfo == c('TotalHHNumber: 3.0'))
B <-H %>% group_by(ClientName) %>% filter(HHMemberInfo == c('TotalHHNumber: 4.0'))
K <- H %>% group_by(ClientName) %>% filter(HHMemberInfo == c('TotalHHNumber: 5.0'))
U <- H %>% group_by(ClientName) %>% filter(HHMemberInfo == c('TotalHHNumber: 6.0'))
Q <-H %>% group_by(ClientName) %>% filter(HHMemberInfo == c('TotalHHNumber: 7.0'))
I <- H %>% group_by(ClientName) %>% filter(HHMemberInfo == c('TotalHHNumber: 8.0'))
L <- H %>% group_by(ClientName) %>% filter(HHMemberInfo == c('TotalHHNumber: 9.0'))
R <-H %>% group_by(ClientName) %>% filter(HHMemberInfo == c('TotalHHNumber: 10.0'))
Z <- H %>% group_by(ClientName) %>% filter(HHMemberInfo == c('TotalHHNumber: 1.0'))

A<- rbind(P,Y)
B <- rbind(B,K)
C <- rbind(U,Q)
D <- rbind(I,L)
E <- rbind(R,Z)
F <- rbind(A,B)
G <- rbind(C,D)
J <- rbind(F,G)
S <- rbind(J,E)
# S here is data set with household member info only have total number of HH member
# we are not considering the HH member greater than 10 at this time. 

# And then, some data visualization. 
# ggplot(S, aes(x = HHMemberInfo, fill = as.factor(Beds))) + geom_bar(position = "stack")+
#   scale_fill_discrete(name = "Beds") +
#   labs (title = "Count:House Hold Total Numbers, Stack: # of Beds")+
#   theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

```

```{r}
bed_dat = S %>%
  mutate(NumPeople = str_replace(HHMemberInfo, "TotalHHNumber: 1.0", '1')) %>%
  mutate(NumPeople = str_replace(NumPeople, "TotalHHNumber: 2.0", '2')) %>%
  mutate(NumPeople = str_replace(NumPeople, "TotalHHNumber: 3.0", '3')) %>%
  mutate(NumPeople = str_replace(NumPeople, "TotalHHNumber: 4.0", '4')) %>%
  mutate(NumPeople = str_replace(NumPeople, "TotalHHNumber: 5.0", '5')) %>%
  mutate(NumPeople = str_replace(NumPeople, "TotalHHNumber: 6.0", '6')) %>%
  mutate(NumPeople = str_replace(NumPeople, "TotalHHNumber: 7.0", '7')) %>%
  mutate(NumPeople = str_replace(NumPeople, "TotalHHNumber: 8.0", '8')) %>%
  mutate(NumPeople = str_replace(NumPeople, "TotalHHNumber: 9.0", '9')) %>%
  mutate(NumPeople = str_replace(NumPeople, "TotalHHNumber: 10.0", '10')) %>%
  filter(Beds != 0) %>%
  filter(!grepl("10", NumPeople))


ggplot(subset(bed_dat,!is.na(Beds)), aes(x = NumPeople, fill = as.factor(Beds))) + 
  geom_bar(position = "stack")+
  scale_fill_discrete(name = "Beds") +
  labs(title = "Number of Total Beds Given By Household Size",
       x="Number of people per Household",
       y="Number of clients")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```
